const mysql = require('./../tool/mysql');
const url = require('url');

const routes = {
    detailsFind: (req, res) => { //查询详情页数据
        const {id} = url.parse( req.url, true ).query;
        // console.log(id)
        const ids = id * 1 // 大坑 mongodb只接收制定类型的数据类型 
        const whereObj = {
           "commonProductInfo.pid":ids
        }
        const showObj = {
            _id:0
        }
        mysql.find('liquor',whereObj,showObj,(data) => {
            // console.log()
             res.send(data[0].commonProductInfo)
        })
    },
    defaultRoute: (req, res) => {
        mysql.find('users', {}, {_id: 0}, (data) => {
            // console
            res.send(data)
            // console.log(data,'是不是报错了')
            // res.send(data)
        })
    },
    insertList: (req, res) => {
        const obj = [
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        },
                        {
                            "type":22,
                            "name":"满减",
                            "wordColor":"#FFFFFF",
                            "backColor":"#c58cff"
                        },
                        {
                            "type":29,
                            "name":"多买多赠",
                            "wordColor":"#FFFFFF",
                            "backColor":"#8888ff"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":25813,
                        "brandId":1,
                        "category":1,
                        "imgPath":"https://img07.jiuxian.com/2018/1110/f19560048c334a328c109b70444f16ec4.jpg",
                        "pname":"【酒仙夜市买一送一】53°茅台 赖茅传承500ml",
                        "jxPrice":799,
                        "actPrice":776,
                        "clubPrice":null,
                        "subTitle":"",
                        "shopId":null,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":true,
                        "deliverMode":true,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        },
                        {
                            "type":29,
                            "name":"买赠",
                            "wordColor":"#FFFFFF",
                            "backColor":"#8888ff"
                        },
                        {
                            "type":34,
                            "name":"单品加价购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#87aef1"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":33699,
                        "brandId":3941,
                        "category":2,
                        "imgPath":"https://img06.jiuxian.com/2016/1230/c6bdbab51b654fe29dd9a1a2d570be934.jpg",
                        "pname":"智利整箱红酒智利干露.克拉克干红葡萄酒750ml（6瓶装）",
                        "jxPrice":269,
                        "actPrice":198,
                        "clubPrice":null,
                        "subTitle":"智利直采名酒，干露酒庄出品",
                        "shopId":null,
                        "noSale":false,
                        "isSelection":true,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":true,
                        "deliverMode":true,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "commonProductInfo":{
                        "pid":88409,
                        "brandId":1,
                        "category":1,
                        "imgPath":"https://img06.jiuxian.com/2019/0516/40bd83898a8c4ee993021ed25a3db4d24.jpg",
                        "pname":"53°茅台迎宾酒（中国红）500ml 单瓶装",
                        "jxPrice":158,
                        "actPrice":158,
                        "clubPrice":null,
                        "subTitle":"",
                        "shopId":1774,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":false,
                        "deliverMode":true,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        },
                        {
                            "type":29,
                            "name":"买赠",
                            "wordColor":"#FFFFFF",
                            "backColor":"#8888ff"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":18239,
                        "brandId":8,
                        "category":1,
                        "imgPath":"https://img10.jiuxian.com/2015/0518/a325506dbe784e9c8b987ef97c306cbb4.jpg",
                        "pname":"52°水井坊臻酿八号500ml",
                        "jxPrice":389,
                        "actPrice":359,
                        "clubPrice":null,
                        "subTitle":"",
                        "shopId":null,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":true,
                        "deliverMode":true,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":22,
                            "name":"满减",
                            "wordColor":"#FFFFFF",
                            "backColor":"#c58cff"
                        },
                        {
                            "type":34,
                            "name":"单品加价购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#87aef1"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":643,
                        "brandId":113,
                        "category":4,
                        "imgPath":"https://img07.jiuxian.com/2016/0127/7919676fa9ea4984a0cbae9a1edb69a54.jpg",
                        "pname":"40°轩尼诗VSOP干邑白兰地700ml",
                        "jxPrice":439,
                        "actPrice":439,
                        "clubPrice":null,
                        "subTitle":"人工采摘干邑产区的葡萄，橡木桶陈酿",
                        "shopId":null,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":true,
                        "deliverMode":true,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        },
                        {
                            "type":23,
                            "name":"阶梯满送",
                            "wordColor":"#FFFFFF",
                            "backColor":"#5eaffe"
                        },
                        {
                            "type":29,
                            "name":"买赠",
                            "wordColor":"#FFFFFF",
                            "backColor":"#8888ff"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":60813,
                        "brandId":2,
                        "category":1,
                        "imgPath":"https://img06.jiuxian.com/2018/0928/0c9381dd92364bd5b77dac1eb5f852364.jpg",
                        "pname":"52°五粮液股份公司出品一尊天下福星高照浓香型白酒礼盒500ml（两瓶装）",
                        "jxPrice":149,
                        "actPrice":139,
                        "clubPrice":null,
                        "subTitle":"五粮液股份公司出品2瓶礼盒装/扫码价488元/盒",
                        "shopId":1403,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":false,
                        "deliverMode":false,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":82857,
                        "brandId":3946,
                        "category":1,
                        "imgPath":"https://img09.jiuxian.com/2019/0702/b729c54ec8464910bba5f21f5aa3aa224.jpg",
                        "pname":"54°鸭溪窖酒500ml+52°鸭溪窖珍品（黑金版）460ml+52°鸭溪窖珍品中国红460ml",
                        "jxPrice":477,
                        "actPrice":208,
                        "clubPrice":null,
                        "subTitle":"",
                        "shopId":null,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":true,
                        "deliverMode":null,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":89893,
                        "brandId":1885,
                        "category":2,
                        "imgPath":"https://img09.jiuxian.com/2019/0612/0e1ba3b2cd174e168ef63a5ed962eada4.jpg",
                        "pname":"中国长城葡萄酒解百纳干红葡萄酒750ml（双支礼盒装）",
                        "jxPrice":88,
                        "actPrice":79,
                        "clubPrice":null,
                        "subTitle":"",
                        "shopId":null,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":true,
                        "deliverMode":null,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        },
                        {
                            "type":29,
                            "name":"多买多赠",
                            "wordColor":"#FFFFFF",
                            "backColor":"#8888ff"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":88640,
                        "brandId":14,
                        "category":1,
                        "imgPath":"https://img08.jiuxian.com/2019/0710/cbb5257a80394f18ab8d3a97d34694744.jpg",
                        "pname":"【酒仙甄选】52°泸州老窖股份老泸州共赏浓香型白酒500ml*6（整箱）",
                        "jxPrice":359,
                        "actPrice":219,
                        "clubPrice":null,
                        "subTitle":"",
                        "shopId":1770,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":false,
                        "deliverMode":true,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                },
                {
                    "promo":[
                        {
                            "type":14,
                            "name":"限时抢购",
                            "wordColor":"#FFFFFF",
                            "backColor":"#ffa855"
                        },
                        {
                            "type":22,
                            "name":"满减",
                            "wordColor":"#FFFFFF",
                            "backColor":"#c58cff"
                        }
                    ],
                    "commonProductInfo":{
                        "pid":3372,
                        "brandId":4,
                        "category":1,
                        "imgPath":"https://img10.jiuxian.com/2016/0331/03c13aa80c9c4dc0b9a5a6c72b04b7754.jpg",
                        "pname":"53°黄盖玻瓶汾酒475ml 3瓶装",
                        "jxPrice":138,
                        "actPrice":135,
                        "clubPrice":null,
                        "subTitle":"",
                        "shopId":null,
                        "noSale":false,
                        "isSelection":false,
                        "videoUrl":null,
                        "imageUrl":null,
                        "showVideoIcon":false,
                        "jxSelf":true,
                        "deliverMode":true,
                        "parallelWarehouse":false,
                        "type":0,
                        "faceIdentify":false,
                        "onSale":true,
                        "inventoryExists":true
                    }
                }
            ]
        
        mysql.insert('liquor',obj,()=>{
            // console.log()
            // if(err) throw err;
            console.log('插入数据成功')
        })
    },
    findList: (req, res) => {
         mysql.find('liquor',{},{_id: 0}, (data) => {
             res.send(data)
         })
    }
}
module.exports = routes;    